name: Basic CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  basic-checks:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.9, 3.11]

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e .[dev]
    
    - name: Basic syntax check
      run: |
        python -m py_compile apps/cli.py
        python -m py_compile apps/muse_cli.py
        python -m py_compile test_benchmarks.py
    
    - name: Run basic tests (if they exist)
      run: |
        python -m pytest tests/ -v --tb=short || echo "Tests failed or don't exist yet"
    
    - name: Check CLI help works
      run: |
        python -m apps.cli --help || echo "CLI help failed"
        python -m apps.muse_cli --help || echo "Muse CLI help failed"
